=== lisuo2013/easy-excel/src/test/resources/easy-excel.dtd
<!-- XML编写约束文档 -->
<!ELEMENT excels (excel)*>
<!ELEMENT excel (field+)>
<!ATTLIST excel id ID #REQUIRED>
<!ATTLIST excel class CDATA #REQUIRED>
<!ATTLIST excel sheetname CDATA #IMPLIED >
<!ATTLIST excel defaultColumnWidth CDATA #IMPLIED >
<!ATTLIST excel defaultAlign (center|left|right) #IMPLIED >
<!ATTLIST excel sheetIndex CDATA #IMPLIED >
<!ATTLIST excel requiredTag (true|false) #IMPLIED >
<!ELEMENT field  EMPTY>
<!ATTLIST field name CDATA #REQUIRED >
<!ATTLIST field title CDATA #REQUIRED >
<!ATTLIST field pattern CDATA #IMPLIED >
<!ATTLIST field format CDATA #IMPLIED >
<!ATTLIST field cellValueConverter CDATA #IMPLIED >
<!ATTLIST field isNull (true|false) #IMPLIED >
<!ATTLIST field regex CDATA #IMPLIED >
<!ATTLIST field regexErrMsg CDATA #IMPLIED >
<!ATTLIST field columnWidth CDATA #IMPLIED >
<!ATTLIST field align (center|left|right) #IMPLIED >
<!ATTLIST field titleBgColor (BLACK|WHITE|RED|BRIGHT_GREEN|BLUE|YELLOW|PINK|TURQUOISE|DARK_RED|GREEN|DARK_BLUE|DARK_YELLOW|VIOLET|TEAL|GREY_25_PERCENT|GREY_50_PERCENT|CORNFLOWER_BLUE|MAROON|LEMON_CHIFFON|ORCHID|CORAL|ROYAL_BLUE|LIGHT_CORNFLOWER_BLUE|SKY_BLUE|LIGHT_TURQUOISE|LIGHT_GREEN|LIGHT_YELLOW|PALE_BLUE|ROSE|LAVENDER|TAN|LIGHT_BLUE|AQUA|LIME|GOLD|LIGHT_ORANGE|ORANGE|BLUE_GREY|GREY_40_PERCENT|DARK_TEAL|SEA_GREEN|DARK_GREEN|OLIVE_GREEN|BROWN|PLUM|INDIGO|GREY_80_PERCENT|AUTOMATIC|black|white|red|bright_green|blue|yellow|pink|turquoise|dark_red|green|dark_blue|dark_yellow|violet|teal|grey_25_percent|grey_50_percent|cornflower_blue|maroon|lemon_chiffon|orchid|coral|royal_blue|light_cornflower_blue|sky_blue|light_turquoise|light_green|light_yellow|pale_blue|rose|lavender|tan|light_blue|aqua|lime|gold|light_orange|orange|blue_grey|grey_40_percent|dark_teal|sea_green|dark_green|olive_green|brown|plum|indigo|grey_80_percent|automatic) #IMPLIED >
<!ATTLIST field titleFountColor (BLACK|WHITE|RED|BRIGHT_GREEN|BLUE|YELLOW|PINK|TURQUOISE|DARK_RED|GREEN|DARK_BLUE|DARK_YELLOW|VIOLET|TEAL|GREY_25_PERCENT|GREY_50_PERCENT|CORNFLOWER_BLUE|MAROON|LEMON_CHIFFON|ORCHID|CORAL|ROYAL_BLUE|LIGHT_CORNFLOWER_BLUE|SKY_BLUE|LIGHT_TURQUOISE|LIGHT_GREEN|LIGHT_YELLOW|PALE_BLUE|ROSE|LAVENDER|TAN|LIGHT_BLUE|AQUA|LIME|GOLD|LIGHT_ORANGE|ORANGE|BLUE_GREY|GREY_40_PERCENT|DARK_TEAL|SEA_GREEN|DARK_GREEN|OLIVE_GREEN|BROWN|PLUM|INDIGO|GREY_80_PERCENT|AUTOMATIC|black|white|red|bright_green|blue|yellow|pink|turquoise|dark_red|green|dark_blue|dark_yellow|violet|teal|grey_25_percent|grey_50_percent|cornflower_blue|maroon|lemon_chiffon|orchid|coral|royal_blue|light_cornflower_blue|sky_blue|light_turquoise|light_green|light_yellow|pale_blue|rose|lavender|tan|light_blue|aqua|lime|gold|light_orange|orange|blue_grey|grey_40_percent|dark_teal|sea_green|dark_green|olive_green|brown|plum|indigo|grey_80_percent|automatic) #IMPLIED >
<!ATTLIST field uniformStyle (true|false) #IMPLIED >
<!ATTLIST field forceText (true|false) #IMPLIED >
<!ATTLIST field decimalFormatPattern CDATA #IMPLIED >
<!ATTLIST field roundingMode (UP|DOWN|CEILING|FLOOR|HALF_UP|HALF_DOWN|HALF_EVEN|UNNECESSARY|up|down|ceiling|floor|half_up|half_down|half_even|unnecessary) #IMPLIED >
<!ATTLIST field otherConfig CDATA #IMPLIED >
<!ATTLIST field defaultValue CDATA #IMPLIED >

=== lisuo2013/easy-excel/src/test/resources/excel-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE excels SYSTEM "easy-excel.dtd">
<excels>
	<!-- excel标签参看:org.easy.excel.config.ExcelDefinition,Field标签参看:org.easy.excel.config.FieldValue -->
	
	<!-- 测试使用 ,学生类-->
	<excel id="student" class="org.easy.excel.test.model.StudentModel" requiredTag="true" sheetname="测试学生列表" defaultAlign="center" sheetIndex="0">
		<field name="id" align="left" titleBgColor="dark_blue" uniformStyle="true" columnWidth="3000" titleFountColor="white" title="ID"/>
		<field name="name" title="学生姓名" uniformStyle="true"/>
		<field name="age" forceText="true" title="年龄" align="right" titleFountColor="red" titleBgColor="dark_blue" isNull="false" regex="^[1-9]\d*$" regexErrMsg="必须是数字"/>
		<field name="studentNo" title="学号" titleFountColor="blue" isNull="false" />
		<field name="createTime" forceText="true" columnWidth="4000" title="创建时间" pattern="yyyy-MM-dd"/>
		<field name="status" title="状态" titleBgColor="green" format="1:正常,0:禁用,-1:无效" />
		<!-- 创建人,可能需要查询数据库校验,这里使用自定义解析器 -->
		<field name="createUser" title="创建人"  cellValueConverter="org.easy.excel.test.converter.CreateUserCellValueConverter" otherConfig="Test动态传递的一个变量"/>
		
		<!-- 复杂对象 -->
		<field name="book.bookName" title="图书名称" columnWidth="6000"/>
		<field name="book.price" title="图书价格" columnWidth="6000" decimalFormatPattern="###,##0.00" roundingMode="up" defaultValue="0.00"/>
		<field name="book.author.authorName" title="作者名称" columnWidth="6000"/>
	</excel>
	
	<!-- 对Map的配置支持 ,class可以写成map或者hashMap都是可以的,java.util.HashMap也是没有问题的,只要是Map接口实现,带无参构造就可以配置-->
	<excel id="studentMap" class="map" requiredTag="true" sheetname="测试学生列表" defaultAlign="center" sheetIndex="0">
		<field name="id" align="left" titleBgColor="dark_blue" uniformStyle="true" columnWidth="3000" titleFountColor="white" title="ID"/>
		<field name="name" title="学生姓名" uniformStyle="true"/>
		<field name="age" title="年龄" align="right" titleFountColor="red" titleBgColor="dark_blue" isNull="false" regex="^[1-9]\d*$" regexErrMsg="必须是数字"/>
		<field name="studentNo" title="学号" titleFountColor="blue" isNull="false" />
		<field name="createTime" columnWidth="4000" title="创建时间" pattern="yyyy-MM-dd"/>
		<field name="status" title="状态" titleBgColor="green" format="1:正常,0:禁用,-1:无效" />
		<!-- 创建人,可能需要查询数据库校验,这里使用自定义解析器 -->
		<field name="createUser" title="创建人"  cellValueConverter="org.easy.excel.test.converter.CreateUserCellValueConverter" otherConfig="Test动态传递的一个变量"/>
		
		<!-- 复杂对象 -->
		<field name="book.bookName" title="图书名称" columnWidth="6000"/>
		<field name="book.price" title="图书价格" columnWidth="6000" decimalFormatPattern="###,##0.00" roundingMode="up" defaultValue="0.00"/>
		<field name="book.author.authorName" title="作者名称" columnWidth="6000"/>
	</excel>
	
	<excel id="student2" class="org.easy.excel.test.model.StudentModel">
		<field name="id" title="ID"/>
		<field name="name" title="学生姓名"/>
		<field name="age" title="年龄" isNull="false" regex="^[1-9]\d*$" regexErrMsg="必须是数字"/>
		<field name="studentNo" title="学号" isNull="false" />
		<field name="createTime" title="创建时间" pattern="yyyy-MM-dd"/>
		<field name="status" title="状态" format="1:正常,0:禁用,-1:无效" />
		<field name="createUser" title="创建人"/>
		<!-- 复杂对象 -->
		<field name="book.bookName" title="图书名称" />
		<field name="book.author.authorName" title="作者名称" isNull="false"/>
	</excel>

	
	<excel id="oneToManyModel" class="org.easy.excel.test.model.OneToManyModel">
		<field name="studentName" title="学生姓名"/>
		<!-- 复杂对象 -->
		<field name="books[0].bookName" title="图书名称1" />
		<field name="books[1].bookName" title="图书名称2" />
	</excel>

	

	
</excels>
